namespace Blanketmen.UnityMcp.Control.Editor
{
    internal static class ControlToolDispatcher
    {
        public static ControlToolCallResponse Dispatch(
            ControlToolCallRequest request,
            UnityControlLogStore logStore,
            string controlVersion,
            MainThreadActionInvoker mainThreadInvoker)
        {
            return request.name switch
            {
                "unity_project_ping" => CoreToolHandlers.HandlePing(controlVersion),
                "unity_project_get_info" => CoreToolHandlers.HandleProjectInfo(request),
                "unity_runtime_get_playmode_status" => CoreToolHandlers.HandlePlaymodeStatus(),
                "unity_runtime_start_playmode" => CoreToolHandlers.HandlePlaymodeStart(request, mainThreadInvoker),
                "unity_runtime_stop_playmode" => CoreToolHandlers.HandlePlaymodeStop(request, mainThreadInvoker),
                "unity_scene_list" => SceneReadToolHandlers.HandleListScenes(request),
                "unity_scene_open" => SceneReadToolHandlers.HandleOpenScene(request),
                "unity_scene_list_loaded" => SceneReadToolHandlers.HandleSceneListLoaded(request),
                "unity_scene_get_active" => SceneReadToolHandlers.HandleSceneGetActive(request),
                "unity_scene_set_active" => SceneReadToolHandlers.HandleSceneSetActive(request),
                "unity_scene_close" => SceneReadToolHandlers.HandleSceneClose(request),
                "unity_gameobject_find" => SceneReadToolHandlers.HandleGoFind(request),
                "unity_gameobject_get" => SceneReadToolHandlers.HandleGameObjectGet(request),
                "unity_component_get_fields" => SceneReadToolHandlers.HandleComponentGetFields(request),
                "unity_component_list" => SceneReadToolHandlers.HandleComponentList(request),
                "unity_component_get_fields_batch" => SceneReadToolHandlers.HandleComponentGetFieldsBatch(request),
                "unity_gameobject_create" => SceneWriteToolHandlers.HandleGoCreate(request),
                "unity_gameobject_delete" => SceneWriteToolHandlers.HandleGoDelete(request),
                "unity_gameobject_duplicate" => SceneWriteToolHandlers.HandleGoDuplicate(request),
                "unity_gameobject_reparent" => SceneWriteToolHandlers.HandleGoReparent(request),
                "unity_gameobject_rename" => SceneWriteToolHandlers.HandleGoRename(request),
                "unity_gameobject_set_active" => SceneWriteToolHandlers.HandleGoSetActive(request),
                "unity_gameobject_set_transform" => SceneWriteToolHandlers.HandleGameObjectSetTransform(request),
                "unity_gameobject_set_tag" => SceneWriteToolHandlers.HandleGameObjectSetTag(request),
                "unity_gameobject_set_layer" => SceneWriteToolHandlers.HandleGameObjectSetLayer(request),
                "unity_gameobject_set_static" => SceneWriteToolHandlers.HandleGameObjectSetStatic(request),
                "unity_scene_create" => SceneWriteToolHandlers.HandleSceneCreate(request),
                "unity_scene_save" => SceneWriteToolHandlers.HandleSceneSave(request),
                "unity_scene_save_all" => SceneWriteToolHandlers.HandleSceneSaveAll(request),
                "unity_component_add" => SceneWriteToolHandlers.HandleComponentAdd(request),
                "unity_component_remove" => SceneWriteToolHandlers.HandleComponentRemove(request),
                "unity_component_set_fields" => SceneWriteToolHandlers.HandleComponentSetFields(request),
                "unity_editor_get_console_logs" => DiagnosticsToolHandlers.HandleGetConsoleLogs(request, logStore),
                "unity_editor_clear_console" => DiagnosticsToolHandlers.HandleClearConsole(logStore),
                "unity_project_run_tests" => DiagnosticsToolHandlers.HandleRunTests(request, mainThreadInvoker),
                "unity_asset_find" => AssetReadToolHandlers.HandleAssetSearch(request),
                "unity_asset_get" => AssetReadToolHandlers.HandleAssetGet(request),
                "unity_asset_get_references" => AssetReadToolHandlers.HandleAssetRefs(request),
                "unity_prefab_get" => PrefabReadToolHandlers.HandlePrefabGet(request),
                "unity_prefab_get_overrides" => PrefabReadToolHandlers.HandlePrefabGetOverrides(request),
                "unity_prefab_create" => PrefabWriteToolHandlers.HandlePrefabCreate(request),
                "unity_prefab_create_instance" => PrefabWriteToolHandlers.HandlePrefabInstantiate(request),
                "unity_prefab_apply_overrides" => PrefabWriteToolHandlers.HandlePrefabApplyOverrides(request),
                "unity_prefab_revert_overrides" => PrefabWriteToolHandlers.HandlePrefabRevertOverrides(request),
                "unity_prefab_unpack" => PrefabWriteToolHandlers.HandlePrefabUnpack(request),
                "unity_prefab_create_variant" => PrefabWriteToolHandlers.HandlePrefabCreateVariant(request),
                "unity_asset_copy" => AssetWriteToolHandlers.HandleAssetCopy(request),
                "unity_asset_create_folder" => AssetWriteToolHandlers.HandleAssetCreateFolder(request),
                "unity_asset_create_text" => AssetWriteToolHandlers.HandleAssetCreateText(request),
                "unity_asset_create_material" => AssetWriteToolHandlers.HandleAssetCreateMaterial(request),
                "unity_asset_create_scriptable_object" => AssetWriteToolHandlers.HandleAssetCreateScriptableObject(request),
                "unity_asset_move" => AssetWriteToolHandlers.HandleAssetMove(request),
                "unity_asset_rename" => AssetWriteToolHandlers.HandleAssetRename(request),
                "unity_asset_delete_to_trash" => AssetWriteToolHandlers.HandleAssetDeleteToTrash(request),
                "unity_asset_reimport" => AssetWriteToolHandlers.HandleAssetReimport(request),
                "unity_asset_import" => AssetWriteToolHandlers.HandleAssetImport(request),
                "unity_asset_set_labels" => AssetWriteToolHandlers.HandleAssetSetLabels(request),
                _ => ControlResponses.NotImplemented(request.name),
            };
        }
    }
}

